{% set name = "mrcfile" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f304c02cb9f0900b26683679c5d3d750da64b5c370b58d69af8a8ddf720c0ce

build:
  noarch: python
  number: 0
  entry_points:
    - mrcfile-header = mrcfile.command_line:print_headers
    - mrcfile-validate = mrcfile.validator:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.16
    - python >=3.6

test:
  imports:
    - mrcfile
  commands:
    - pip check
    - mrcfile-header
  requires:
    - pip

about:
  home: https://github.com/ccpem/mrcfile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MRC file I/O library
  description: |
    mrcfile is a Python implementation of the MRC2014 file format
    (http://www.ccpem.ac.uk/mrc_format/mrc2014.php), which is used in
    structural biology to store image and volume data.

    It allows MRC files to be created and opened easily using a very
    simple API, which exposes the file's header and data as numpy
    arrays. The code runs in Python 2 and 3 and is fully unit-tested.

    This library aims to allow users and developers to read and write
    standard-compliant MRC files in Python as easily as possible, and
    with no dependencies on any compiled libraries except numpy. You can
    use it interactively to inspect files, correct headers and so on, or
    in scripts and larger software packages to provide basic MRC file
    I/O functions.
  doc_url: https://mrcfile.readthedocs.io
  dev_url: https://github.com/ccpem/mrcfile

extra:
  recipe-maintainers:
    - colinpalmer
    - bkpoon
    - anthchirp
